let k = {
  kind: "youtube#playlistItemListResponse",
  etag: "TD8boqWceRKNDMACnVwhqq1JawA",
  items: [
    {
      kind: "youtube#playlistItem",
      etag: "VE1rGgdDAATYT0NVh5y8oRPNXls",
      id: "VVVMSWRxSDdQVXNtelBkTEZjeVFNNW93LkJlQndpZTlia1pr",
      snippet: {
        publishedAt: "2023-03-10T12:03:04Z",
        channelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
        title: "Paragliding.",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/BeBwie9bkZk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/BeBwie9bkZk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/BeBwie9bkZk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/BeBwie9bkZk/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/BeBwie9bkZk/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Hriday Mahajan",
        playlistId: "UULIdqH7PUsmzPdLFcyQM5ow",
        position: 0,
        resourceId: { kind: "youtube#video", videoId: "BeBwie9bkZk" },
        videoOwnerChannelTitle: "Hriday Mahajan",
        videoOwnerChannelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
      },
    },
    {
      kind: "youtube#playlistItem",
      etag: "WQA8muA2UOGOveumJ1Sjg87KGHs",
      id: "VVVMSWRxSDdQVXNtelBkTEZjeVFNNW93LmpkTElDSHBDN0xn",
      snippet: {
        publishedAt: "2023-01-29T10:45:04Z",
        channelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
        title: "29 January 2023",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/jdLICHpC7Lg/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/jdLICHpC7Lg/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/jdLICHpC7Lg/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/jdLICHpC7Lg/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/jdLICHpC7Lg/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Hriday Mahajan",
        playlistId: "UULIdqH7PUsmzPdLFcyQM5ow",
        position: 1,
        resourceId: { kind: "youtube#video", videoId: "jdLICHpC7Lg" },
        videoOwnerChannelTitle: "Hriday Mahajan",
        videoOwnerChannelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
      },
    },
    {
      kind: "youtube#playlistItem",
      etag: "bIEMImvXz726zCG7AZxny8WFNp0",
      id: "VVVMSWRxSDdQVXNtelBkTEZjeVFNNW93LnlvOENUcEhfNzBB",
      snippet: {
        publishedAt: "2023-01-28T11:12:48Z",
        channelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
        title: "A good vibe.",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/yo8CTpH_70A/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/yo8CTpH_70A/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/yo8CTpH_70A/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/yo8CTpH_70A/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/yo8CTpH_70A/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Hriday Mahajan",
        playlistId: "UULIdqH7PUsmzPdLFcyQM5ow",
        position: 2,
        resourceId: { kind: "youtube#video", videoId: "yo8CTpH_70A" },
        videoOwnerChannelTitle: "Hriday Mahajan",
        videoOwnerChannelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
      },
    },
    {
      kind: "youtube#playlistItem",
      etag: "tQSStw0m9VSX0Mpa-5Ax6icCcD4",
      id: "VVVMSWRxSDdQVXNtelBkTEZjeVFNNW93LnVMV0lYTjRtWUpN",
      snippet: {
        publishedAt: "2021-12-31T12:47:17Z",
        channelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
        title: "Merry Christmas🎄🎂🥳",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/uLWIXN4mYJM/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/uLWIXN4mYJM/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/uLWIXN4mYJM/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/uLWIXN4mYJM/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/uLWIXN4mYJM/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Hriday Mahajan",
        playlistId: "UULIdqH7PUsmzPdLFcyQM5ow",
        position: 3,
        resourceId: { kind: "youtube#video", videoId: "uLWIXN4mYJM" },
        videoOwnerChannelTitle: "Hriday Mahajan",
        videoOwnerChannelId: "UCLIdqH7PUsmzPdLFcyQM5ow",
      },
    },
  ],
  pageInfo: { totalResults: 4, resultsPerPage: 10 },
};
